pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         stage('Clone repository') {
            steps {
                script{
                checkout scm
                }
            }
        }

        stage('Build') {
            steps {
                script{
                 app = docker.build("flask-app")
                }
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
        stage('Deploy') {
            steps {
                script{
                        docker.withRegistry('https://quay.io/george-mikulich/flask-app','4b2b06c7-5ea6-4ef4-b1fc-6ff48c45c9c3') {
                    app.push("1.0")
                    }
                }
            }
        }
    }
}
