apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.appLabel }}
        ports:
        - containerPort: {{ .Values.containerPort }}
